version: "1"
rules:                        # Array of rules
  - base: master              # Required. Target branch
    upstream: snaptec:master  # Required. Must be in the same fork network.
    mergeMethod: rebase       # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false      # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: updatemine
    upstream: snaptec:master
    mergeMethod: rebase
    mergeUnstable: false
  - base: securitySettings
    upstream: snaptec:master 
    mergeMethod: rebase 
    mergeUnstable: false
